seed: 3241

### data ###
data_root: "data/NYU"
remote_data_root: "/cluster_home/custom_data/NYU"
remote_save_dir: "/job_data"
save_dir: "data/NYU/output"
batch_size: 16
input_size: (320,320)
output_size: (320,320)

### model ###
task: 'multitask'
learning_rate: 2e-5
use_gradnorm: False

### lightning ###
lightning:
  max_epochs: 1540
  gpus: 4
  check_val_every_n_epoch: 10
  accelerator: "ddp"
  log_every_n_steps: 5
  num_sanity_val_steps: 0
  precision: 16
  
