seed: 1822

### data ###
data_root: "data/NYU"
remote_data_root: "/cluster_home/custom_data/NYU"
remote_save_dir: "/job_data"
batch_size: 1

### model ###
task: 'segmentation'
learning_rate: 2e-5
use_gradnorm: True

### lightning ###
lightning:
  max_epochs: 8890
  gpus: 1,3
  check_val_every_n_epoch: 1
  accelerator: "ddp"
  log_every_n_steps: 5
  num_sanity_val_steps: 0
